export default {
  flag: "Flag",
  quiz: "Quiz",
  homeLetsGo: "Let's go!",
  name: "Name",
  numberOfRounds: "Number of rounds",
  userInputScreenHint: "Pick a name and choose a number of rounds to play:",
  start: "Start",
  correct: "Correct!",
  wrong: "Wrong...",
  congratulations: "Congratulations! You finished the quiz!",
  yourScore: "Your score was:",
  questionsSeparately: "Your answers:",
  home: "Home",
  returnToHome: "If you want to play again, click this button",
  next: "Next",
  nameErrorText: "\nName cannot be empty\n",
  roundsErrorText: "Number of rounds must be between 1 and 99",
  alertErrorText: "Something is not quite right...",
};
